import { useState } from 'react'
import { Alert, Share, StyleSheet, Text, View } from 'react-native'
import { AppScreen, SectionCard, GradientButton, Badge, Spacer } from '../../../src/components/MobileUI'
import { useRecord } from '../../../src/providers/RecordProvider'
import { useAuth } from '../../../src/providers/AuthProvider'
import { useSubscription } from '../../../src/providers/SubscriptionProvider'
import { colors, typography, shadows, radii, spacing } from '../../../src/theme/colors'

function buildSummary(record: any): string {
  const patient = record?.patient || {}
  const vitals = Array.isArray(record?.vitals) ? record.vitals : []
  const medications = Array.isArray(record?.medications) ? record.medications : []
  const appointments = Array.isArray(record?.appointments) ? record.appointments : []
  const reports = Array.isArray(record?.reports) ? record.reports : []
  const timeline = Array.isArray(record?.timeline) ? record.timeline : []

  const lines: string[] = []
  lines.push('=== HealthMap AI — Health Summary ===')
  lines.push('')

  if (patient.name) lines.push(`Name: ${patient.name}`)
  if (patient.dob || patient.dateOfBirth) lines.push(`DOB: ${patient.dob || patient.dateOfBirth}`)
  if (patient.bloodGroup) lines.push(`Blood Group: ${patient.bloodGroup}`)
  lines.push('')

  if (vitals.length > 0) {
    lines.push('--- Vitals ---')
    vitals.slice(0, 10).forEach((v: any) => {
      lines.push(`  ${v.type || 'Vital'}: ${v.value || ''} ${v.unit || ''} (${v.date || ''})`)
    })
    lines.push('')
  }

  if (medications.length > 0) {
    lines.push('--- Medications ---')
    medications.forEach((m: any) => {
      lines.push(`  ${m.name || 'Medication'} — ${m.dosage || ''} ${m.frequency || ''} [${m.status || 'Active'}]`)
    })
    lines.push('')
  }

  if (appointments.length > 0) {
    lines.push('--- Appointments ---')
    appointments.slice(0, 10).forEach((a: any) => {
      lines.push(`  ${a.title || a.doctor || 'Appointment'} — ${a.date || ''}`)
    })
    lines.push('')
  }

  if (reports.length > 0) {
    lines.push('--- Reports ---')
    reports.slice(0, 10).forEach((r: any) => {
      lines.push(`  ${r.name || r.title || 'Report'} — ${r.date || ''}`)
    })
    lines.push('')
  }

  if (timeline.length > 0) {
    lines.push('--- Timeline ---')
    timeline.slice(0, 10).forEach((t: any) => {
      lines.push(`  ${t.title || 'Event'}: ${t.details || t.description || ''} (${t.date || ''})`)
    })
    lines.push('')
  }

  lines.push('Generated by HealthMap AI')
  return lines.join('\n')
}

function buildDoctorSummary(record: any, userName: string): string {
  const patient = record?.patient || {}
  const emergency = record?.emergencyInfo || {}
  const vitals = Array.isArray(record?.vitals) ? record.vitals : []
  const medications = Array.isArray(record?.medications) ? record.medications : []
  const appointments = Array.isArray(record?.appointments) ? record.appointments : []

  const lines: string[] = []
  lines.push('=== Patient Summary for Doctor ===')
  lines.push('')
  lines.push(`Patient: ${patient.name || userName || 'N/A'}`)
  if (patient.dob || patient.dateOfBirth) lines.push(`DOB: ${patient.dob || patient.dateOfBirth}`)
  if (patient.bloodGroup) lines.push(`Blood Group: ${patient.bloodGroup}`)
  if (patient.conditions?.length) lines.push(`Conditions: ${patient.conditions.join(', ')}`)
  if (patient.allergies?.length) lines.push(`Allergies: ${patient.allergies.join(', ')}`)
  if (emergency.allergies?.length) lines.push(`Emergency Allergies: ${emergency.allergies.join(', ')}`)
  lines.push('')

  if (vitals.length > 0) {
    lines.push('--- Recent Vitals ---')
    vitals.slice(0, 5).forEach((v: any) => {
      lines.push(`  ${v.type || 'Vital'}: ${v.value || ''} ${v.unit || ''} (${v.date || ''})`)
    })
    lines.push('')
  }

  if (medications.length > 0) {
    lines.push('--- Current Medications ---')
    medications
      .filter((m: any) => m.status === 'Active' || m.status === 'active' || !m.status)
      .forEach((m: any) => {
        lines.push(`  ${m.name || 'Medication'} — ${m.dosage || ''} ${m.frequency || ''}`)
      })
    lines.push('')
  }

  if (appointments.length > 0) {
    lines.push('--- Upcoming Appointments ---')
    appointments.slice(0, 5).forEach((a: any) => {
      lines.push(`  ${a.title || a.doctor || 'Appointment'} — ${a.date || ''}`)
    })
    lines.push('')
  }

  lines.push('Generated by HealthMap AI')
  return lines.join('\n')
}

export default function ExportScreen() {
  const { record } = useRecord()
  const { user } = useAuth()
  const { hasFeature } = useSubscription()
  const [sharing, setSharing] = useState(false)

  const handleExportSummary = async () => {
    setSharing(true)
    try {
      const summary = buildSummary(record)
      await Share.share({ message: summary, title: 'Health Summary' })
    } catch (err: any) {
      if (err?.message !== 'User did not share') {
        Alert.alert('Error', 'Could not share. Please try again.')
      }
    } finally {
      setSharing(false)
    }
  }

  const handleShareWithDoctor = async () => {
    setSharing(true)
    try {
      const summary = buildDoctorSummary(record, user?.fullName || '')
      await Share.share({ message: summary, title: 'Patient Summary for Doctor' })
    } catch (err: any) {
      if (err?.message !== 'User did not share') {
        Alert.alert('Error', 'Could not share. Please try again.')
      }
    } finally {
      setSharing(false)
    }
  }

  const handleDownloadPdf = () => {
    if (!hasFeature('exportPdf' as any)) {
      Alert.alert('Premium Feature', 'PDF export is available on the Premium plan. Upgrade to unlock this feature.')
      return
    }
    Alert.alert('Coming in v1.1', 'PDF health report export is being built and will be available in the next update. Use text export for now.')
  }

  const canExportPdf = hasFeature('exportPdf' as any)

  return (
    <AppScreen>
      <Text style={styles.heading}>Export & Share</Text>
      <Text style={styles.subheading}>
        Share your health data with doctors or save a copy for your records.
      </Text>

      <Spacer size={spacing.xl} />

      {/* Export Summary */}
      <SectionCard title="Export Summary">
        <Text style={styles.cardDescription}>
          Generate a complete text summary of your health record including vitals, medications,
          reports, and timeline entries.
        </Text>
        <Spacer size={spacing.md} />
        <GradientButton
          label={sharing ? 'Sharing...' : 'Share Summary'}
          onPress={handleExportSummary}
          disabled={sharing}
          icon="\u{1F4CB}"
        />
      </SectionCard>

      <Spacer size={spacing.lg} />

      {/* Share with Doctor */}
      <SectionCard title="Share with Doctor">
        <Text style={styles.cardDescription}>
          Generate a formatted patient summary optimized for doctor visits. Includes patient info,
          vitals, active medications, and upcoming appointments.
        </Text>
        <Spacer size={spacing.md} />
        <GradientButton
          label={sharing ? 'Sharing...' : 'Share with Doctor'}
          onPress={handleShareWithDoctor}
          disabled={sharing}
          icon="\u{1FA7A}"
        />
      </SectionCard>

      <Spacer size={spacing.lg} />

      {/* Download PDF */}
      <SectionCard title="Download PDF">
        <View style={styles.pdfRow}>
          <Text style={styles.cardDescription}>
            Export a beautifully formatted PDF of your complete health record.
          </Text>
          {!canExportPdf && (
            <Badge label="Premium" tone="gold" icon="\u{1F451}" />
          )}
        </View>
        <Spacer size={spacing.md} />
        <GradientButton
          label={canExportPdf ? 'Download PDF' : 'Upgrade to Unlock'}
          onPress={handleDownloadPdf}
          disabled={!canExportPdf}
          colors={canExportPdf ? colors.gradientPrimary : undefined}
          icon={canExportPdf ? '\u{1F4C4}' : '\u{1F512}'}
        />
      </SectionCard>

      <Spacer size={spacing.xxxl} />
    </AppScreen>
  )
}

const styles = StyleSheet.create({
  heading: {
    ...typography.h2,
    color: colors.text,
  },
  subheading: {
    ...typography.body,
    color: colors.textMuted,
    marginTop: spacing.xs,
  },
  cardDescription: {
    ...typography.body,
    color: colors.textSecondary,
  },
  pdfRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
})
